#389 Find the Difference
# You are given two strings s and t.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Return the letter that was added to t.

class Solution(object):
    def findTheDifference1(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        list_s = sorted(list(s))
        list_t = sorted(list(t))
        for i in range(len(list_s)):
            if list_t[i]!=list_s[i]: return list_t[i]
        return list_t[-1]

    def findTheDifference2(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        counter_s = Counter(s)
        counter_t = Counter(t)
        for el in counter_t:
            if el not in counter_s or counter_s[el] != counter_t[el]:
                return el
